_type: export
__export_format: 4
__export_date: 2022-05-16T01:21:43.976Z
__export_source: insomnia.desktop.app:v2022.3.0
resources:
  - _id: req_af5bed3f67234953823bfa481f43fadf
    parentId: fld_230b8e8ed6cd418ebb241eaae621a391
    modified: 1652663585203
    created: 1652040248924
    url: "{{ _.URL }}/salas/"
    name: Cadastrar
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: |-
        {
        	"numero": 1,
        	"capacidade": 18,
        	"disponivel": true,
        	"professor_matricula": 1
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
        id: pair_7854cd6a2def4da58c3a8946840182cb
    authentication: {}
    metaSortKey: -1652137439900
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: fld_230b8e8ed6cd418ebb241eaae621a391
    parentId: wrk_0b9d21bb29be4de19e6fa1074b61b2d4
    modified: 1652038096118
    created: 1652038096118
    name: Sala
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1652038096118
    _type: request_group
  - _id: wrk_0b9d21bb29be4de19e6fa1074b61b2d4
    parentId: null
    modified: 1651788643789
    created: 1651788643789
    name: New Document
    description: ""
    scope: design
    _type: workspace
  - _id: req_46e411da0b9443989fa39c041f2a5148
    parentId: fld_230b8e8ed6cd418ebb241eaae621a391
    modified: 1652487200412
    created: 1652137439850
    url: "{{ _.URL }}/salas/1"
    name: Consultar
    description: ""
    method: GET
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1652137439850
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_11ca2a586acb4cf8a76613f62282699d
    parentId: fld_230b8e8ed6cd418ebb241eaae621a391
    modified: 1652663594477
    created: 1652137503800
    url: "{{ _.URL }}/salas/1"
    name: Atualizar
    description: ""
    method: PUT
    body:
      mimeType: application/json
      text: |-
        {
        	"capacidade": 2,
        	"disponivel": true
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
        id: pair_29a00815bf3f46cf8ea48dbca1e945b2
    authentication: {}
    metaSortKey: -1652137205494
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_1d815054cc1c448b90d06b9d44cd2a22
    parentId: fld_230b8e8ed6cd418ebb241eaae621a391
    modified: 1652487206207
    created: 1652137869639
    url: "{{ _.URL }}/salas/1"
    name: Deletar
    description: ""
    method: DELETE
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1652088727196.5
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_b03bf3740e704bbda1542ed9773fcece
    parentId: fld_230b8e8ed6cd418ebb241eaae621a391
    modified: 1652648304608
    created: 1652137832527
    url: "{{ _.URL }}/salas/1/verAlunos"
    name: Consultar Alunos de uma sala
    description: ""
    method: GET
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1652040248899
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_dfd4eded13c34afebba3c40acb5955d1
    parentId: fld_230b8e8ed6cd418ebb241eaae621a391
    modified: 1652663718457
    created: 1652131533763
    url: "{{ _.URL }}/salas/1/addAluno/1"
    name: Adicionar Aluno a Sala
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: |-
        {
        	"professor_matricula": 1
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
        id: pair_07ed41778e2341b5a20964a3f6e99cca
    authentication: {}
    metaSortKey: -1652040248874
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_1001ff0ebbe04d1cb57ac949f0687634
    parentId: fld_230b8e8ed6cd418ebb241eaae621a391
    modified: 1652651459239
    created: 1652137331515
    url: "{{ _.URL }}/salas/1/delAluno/1"
    name: Remover Aluno da Sala
    description: ""
    method: DELETE
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1651914446402.2188
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_eac0d4e93ce44b5fb66ee11babfbf75c
    parentId: fld_6b449bb3c5194881883f8dbc8bf70b04
    modified: 1652663246309
    created: 1651788643832
    url: "{{ _.URL }}/alunos"
    name: Cadastrar
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: |-
        {
        	"matricula" : 1,
        	"nome" : "Daniel José Martins Cruz",
        	"email" : "daniel@teste.com",
        	"data_nasc" : "19/03/1999"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
        id: pair_8cf8262a177a4b5d99a27d25732a72d7
    authentication: {}
    metaSortKey: -1652136971188
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: fld_6b449bb3c5194881883f8dbc8bf70b04
    parentId: wrk_0b9d21bb29be4de19e6fa1074b61b2d4
    modified: 1652137064119
    created: 1652025280659
    name: Aluno
    description: ""
    environment: {}
    environmentPropertyOrder: {}
    metaSortKey: -1652025280659
    _type: request_group
  - _id: req_5e8fbe49ff1a4a60ae2cbcd4486e34b2
    parentId: fld_6b449bb3c5194881883f8dbc8bf70b04
    modified: 1652631525457
    created: 1652025335762
    url: "{{ _.URL }}/alunos/1"
    name: Consultar
    description: ""
    method: GET
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1652136971163
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_ffd6e0a52c834ebe8d07cc9289cd0fb8
    parentId: fld_6b449bb3c5194881883f8dbc8bf70b04
    modified: 1652663061097
    created: 1652025339123
    url: "{{ _.URL }}/alunos/1"
    name: Atualizar
    description: ""
    method: PUT
    body:
      mimeType: application/json
      text: |-
        {
        	"data_nasc": "19/04/1999"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
        id: pair_8cf8262a177a4b5d99a27d25732a72d7
    authentication: {}
    metaSortKey: -1652136971150.5
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_aa967e43b2214751a88d923b08bf867f
    parentId: fld_6b449bb3c5194881883f8dbc8bf70b04
    modified: 1652660233805
    created: 1652024762525
    url: "{{ _.URL }}/alunos/1"
    name: Deletar
    description: ""
    method: DELETE
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1652136971144.25
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_62a970fe3c34440c83502fd38d1b25a4
    parentId: fld_6b449bb3c5194881883f8dbc8bf70b04
    modified: 1652660237503
    created: 1652136971138
    url: "{{ _.URL }}/alunos/1/listarSalas"
    name: Listar salas do aluno
    description: ""
    method: GET
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1652136971138
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_600b2465515c40cca18ea5d0dd4db688
    parentId: fld_16c6f61493274d6ba53c09eaa95e3c58
    modified: 1652663077787
    created: 1652025330022
    url: "{{ _.URL }}/professores"
    name: Cadastrar
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: |-
        {
        	"matricula" : 1 ,
        	"nome" : "Elon Musk",
        	"email" : "elon@spacex.com",
        	"data_nasc" : "28/06/1971"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
        id: pair_8cf8262a177a4b5d99a27d25732a72d7
    authentication: {}
    metaSortKey: -1651788643930.4375
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: fld_16c6f61493274d6ba53c09eaa95e3c58
    parentId: wrk_0b9d21bb29be4de19e6fa1074b61b2d4
    modified: 1652040299834
    created: 1652025261427
    name: Professor
    description: ""
    environment: {}
    environmentPropertyOrder: {}
    metaSortKey: -1652025261427
    _type: request_group
  - _id: req_81b4ea6e6f9143ce91f8b62a9eb2f3d7
    parentId: fld_16c6f61493274d6ba53c09eaa95e3c58
    modified: 1652660306454
    created: 1652023845415
    url: "{{ _.URL }}/professores/1"
    name: Consultar
    description: ""
    method: GET
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1651788643880.4375
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_8b21b35fe4e9472581cc201ead1c5f03
    parentId: fld_16c6f61493274d6ba53c09eaa95e3c58
    modified: 1652663076012
    created: 1652023915732
    url: "{{ _.URL }}/professores/1"
    name: Atualizar
    description: ""
    method: PUT
    body:
      mimeType: application/json
      text: |-
        {
        	"nome" : "Elon Musk da Silva"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
        id: pair_8cf8262a177a4b5d99a27d25732a72d7
    authentication: {}
    metaSortKey: -1651788643855.4375
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_d702a5cfebe743868c9ae299b6fc7260
    parentId: fld_16c6f61493274d6ba53c09eaa95e3c58
    modified: 1652660321707
    created: 1652025340765
    url: "{{ _.URL }}/professores/1"
    name: Deletar
    description: ""
    method: DELETE
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1651788643842.9375
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: env_5637ff7daeecf346843b2b5837d4f8b13f9cf2c4
    parentId: wrk_0b9d21bb29be4de19e6fa1074b61b2d4
    modified: 1651793840022
    created: 1651788643820
    name: Base Environment
    data: {}
    dataPropertyOrder: {}
    color: null
    isPrivate: false
    metaSortKey: 1651788643820
    _type: environment
  - _id: jar_5637ff7daeecf346843b2b5837d4f8b13f9cf2c4
    parentId: wrk_0b9d21bb29be4de19e6fa1074b61b2d4
    modified: 1651788643825
    created: 1651788643825
    name: Default Jar
    cookies: []
    _type: cookie_jar
  - _id: spc_f5f3dbbe27d0478ca6ead06f1a8145bf
    parentId: wrk_0b9d21bb29be4de19e6fa1074b61b2d4
    modified: 1651793749911
    created: 1651788643812
    fileName: Rooms
    contents: ""
    contentType: yaml
    _type: api_spec
  - _id: uts_84604c01430f476abae593e6d2a571b7
    parentId: wrk_0b9d21bb29be4de19e6fa1074b61b2d4
    modified: 1651788643836
    created: 1651788643836
    name: Example Test Suite
    _type: unit_test_suite
  - _id: env_7f952085132b4204b96b5b1d80a299e1
    parentId: env_5637ff7daeecf346843b2b5837d4f8b13f9cf2c4
    modified: 1652484100079
    created: 1651793891895
    name: Rooms
    data:
      URL: http://localhost:3000
    dataPropertyOrder:
      "&":
        - URL
    color: null
    isPrivate: false
    metaSortKey: 1651793891895
    _type: environment
